---
- name: install Ansible dependencies
  apt: name=software-properties-common state=latest

- name: add Ansible APT repository
  apt_repository: repo="ppa:ansible/ansible" state=present

- name: install Ansible
  apt: name=ansible state=latest update_cache=yes cache_valid_time=3600
